name: Docker Build Multi-version

on:
  workflow_dispatch:  # 手动触发
    inputs:
      versions:
        description: '生成多版本'
        required: false
        default: '6.0-10.0'
        type: string
      push:
        description: 'Push to registry'
        required: false
        default: 'true'
        type: boolean

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/notapp
  DOCKERFILE_DIR: NotCoreApp
  Max_Version: '10.0'

jobs:
  build-multi-version:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        dotnet_version: ['6.0', '6.0-alpine', '7.0', '7.0-alpine', '8.0', '8.0-alpine', '9.0', '9.0-alpine', '10.0', '10.0-alpine']
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event.inputs.push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Generate tags
        id: tags
        run: |
          VERSION=${{ matrix.dotnet_version }}
          echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          VERSION=${{ matrix.dotnet_version }}
          
          # 使用ARG传递.NET版本
          docker build \
            --build-arg DOTNET_VERSION=$VERSION \
            -t ${{ steps.tags.outputs.TAGS }} \
            ${{ env.DOCKERFILE_DIR }}

      - name: Push Docker image
        if: github.event.inputs.push == 'true'
        run: |
          # 推送版本标签
          docker push ${{ steps.tags.outputs.TAGS }}
